// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createMockSupabaseClient() {
  const listeners = new Set<(event: string, session: any) => void>();
  let currentSession: any = (() => {
    try {
      const stored = localStorage.getItem('exora_demo_session');
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  })();

  const auth = {
    onAuthStateChange(callback: (event: string, session: any) => void) {
      listeners.add(callback);
      // Immediately notify of current state
      setTimeout(() => callback(currentSession ? 'SIGNED_IN' : 'SIGNED_OUT', currentSession), 0);
      return {
        data: {
          subscription: {
            unsubscribe: () => listeners.delete(callback),
          },
        },
      };
    },
    async getSession() {
      return { data: { session: currentSession }, error: null };
    },
    async getUser() {
      return { data: { user: currentSession?.user ?? null }, error: null };
    },
    async signUp({ email, options }: any) {
      const displayName = options?.data?.display_name || email.split('@')[0];
      currentSession = {
        access_token: 'mock-token-' + Date.now(),
        user: {
          id: 'user-' + Date.now(),
          email,
          user_metadata: { display_name: displayName },
        },
      };
      try {
        localStorage.setItem('exora_demo_session', JSON.stringify(currentSession));
      } catch {}
      listeners.forEach((l) => l('SIGNED_IN', currentSession));
      return { data: { user: currentSession.user, session: currentSession }, error: null };
    },
    async signInWithPassword({ email }: any) {
      currentSession = {
        access_token: 'mock-token-' + Date.now(),
        user: {
          id: 'user-' + Date.now(),
          email,
          user_metadata: { display_name: email.split('@')[0] },
        },
      };
      try {
        localStorage.setItem('exora_demo_session', JSON.stringify(currentSession));
      } catch {}
      listeners.forEach((l) => l('SIGNED_IN', currentSession));
      return { data: { user: currentSession.user, session: currentSession }, error: null };
    },
    async signOut() {
      currentSession = null;
      try {
        localStorage.removeItem('exora_demo_session');
      } catch {}
      listeners.forEach((l) => l('SIGNED_OUT', null));
      return { error: null };
    },
    async setSession(tokens: any) {
      const email = tokens?.user?.email || tokens?.email || 'trader@exora.trade';
      const displayName =
        tokens?.user?.user_metadata?.display_name ||
        tokens?.name ||
        tokens?.user?.user_metadata?.name ||
        email.split('@')[0] ||
        'Trader';
      const avatarUrl =
        tokens?.user?.user_metadata?.avatar_url ||
        tokens?.picture ||
        tokens?.avatar_url ||
        '';
      const id = tokens?.user?.id || tokens?.id || ('google-' + Date.now());

      currentSession = {
        access_token: tokens?.access_token || 'token-' + Date.now(),
        user: {
          id,
          email,
          user_metadata: {
            display_name: displayName,
            avatar_url: avatarUrl,
            provider: tokens?.provider || 'google',
          },
        },
      };
      try {
        localStorage.setItem('exora_demo_session', JSON.stringify(currentSession));
      } catch {}
      listeners.forEach((l) => l('SIGNED_IN', currentSession));
      return { data: { session: currentSession, user: currentSession.user }, error: null };
    },
  };

  const queryBuilder = {
    select: () => queryBuilder,
    insert: async (data: any) => ({ data, error: null }),
    update: async (data: any) => ({ data, error: null }),
    delete: async () => ({ data: null, error: null }),
    eq: () => queryBuilder,
    order: () => queryBuilder,
    limit: () => queryBuilder,
    single: async () => ({ data: null, error: null }),
    then: (resolve: any) => resolve({ data: [], error: null }),
  };

  return {
    auth,
    from: () => queryBuilder,
    rpc: async () => ({ data: null, error: null }),
  } as any;
}

function createSupabaseClient() {
  const SUPABASE_URL = (typeof import.meta !== 'undefined' && import.meta.env?.['VITE_SUPABASE_URL']) || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = (typeof import.meta !== 'undefined' && import.meta.env?.['VITE_SUPABASE_PUBLISHABLE_KEY']) || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Environment variables not configured — using resilient pilot mock.');
    return createMockSupabaseClient();
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (err) {
    console.warn('[Supabase] Initialization failed, falling back to mock:', err);
    return createMockSupabaseClient();
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

